// Type declarations for @liquicode/jsonstor-excel
//
// Generated by jsonstor-docs/build/build-adapter-docs.js from docs/data/adapters.js.
// Edits here are erased by the next build.
//
// Documents are stored in an Excel spreadsheet file.

declare module '@liquicode/jsonstor-excel'
{

	//---------------------------------------------------------------------
	// The settings this adapter takes.

	export interface AdapterSettings
	{
		/** Path to the Excel or CSV file storing the data. */
		Path: string;
		/** The name of the worksheet storing the data. */
		SheetName: string;
		/** Write the workbook on every insert, update, replace, and delete. Defaults to `true`. */
		AutoFlush?: boolean;
		/** The row index of the header row, which names the document fields. Defaults to `0`. */
		HeaderRow?: number;
		/** The row index the data starts on. Defaults to `1`. */
		DataRow?: number;
		/** The column index the data starts on. Defaults to `0`. */
		DataCol?: number;
	}


	//---------------------------------------------------------------------
	// The storage this adapter returns.
	//
	// Its members belong to jsonstor rather than to any adapter, so they are left open
	// here rather than restated - an adapter which described them would be describing
	// the storage interface, which is not its to describe.

	export interface Storage
	{
		[ MemberName: string ]: any;
	}


	//---------------------------------------------------------------------
	// The adapter itself. This is what `require()` returns, and what you hand to
	// `jsonstor.LoadPlugin()`.

	export interface StorageAdapter
	{
		/** Always `'jsonstor-excel'`. The name this adapter registers under. */
		AdapterName: string;
		AdapterDescription: string;
		GetAdapter( jsonstor: any, Settings: AdapterSettings ): Storage;
	}


	//---------------------------------------------------------------------
	// The default export is the adapter, and is what `require()` returns.

	const adapter: StorageAdapter;
	export default adapter;


	//---------------------------------------------------------------------
	// Named exports, matching src/jsonstor-excel.mjs one for one.

	export const AdapterName: string;
	export const AdapterDescription: string;
	export const GetAdapter: StorageAdapter[ 'GetAdapter' ];

}
